import { Place, Experience, EsimPlan } from "@/types";

export const MOCK_PLACES: Place[] = [
  {
    id: "p1",
    name: "Le Bernardin",
    category: "restaurant",
    address: "155 W 51st St",
    city: "New York",
    lat: 40.7614,
    lng: -73.9817,
    rating: 4.8,
    reviewCount: 2341,
    priceLevel: 4,
    description: "Legendary French seafood temple with an extraordinary tasting menu.",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    source: "tripadvisor",
    phone: "+1 212-554-1515",
    hours: "Mon–Fri 12–2:30pm, 5:15–10:30pm",
    tags: ["French", "Seafood", "Fine Dining", "Michelin Star"],
  },
  {
    id: "p2",
    name: "Central Park",
    category: "park",
    address: "Central Park, Manhattan",
    city: "New York",
    lat: 40.7851,
    lng: -73.9683,
    rating: 4.9,
    reviewCount: 87432,
    priceLevel: 1,
    description: "843-acre urban oasis with meadows, lakes, and iconic skyline views.",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=600&q=80",
    source: "tripadvisor",
    hours: "Open 24 hours",
    tags: ["Park", "Nature", "Sightseeing", "Family-Friendly"],
  },
  {
    id: "p3",
    name: "Shake Shack",
    category: "restaurant",
    address: "691 8th Ave",
    city: "New York",
    lat: 40.7577,
    lng: -73.9891,
    rating: 4.4,
    reviewCount: 5678,
    priceLevel: 2,
    description: "Modern roadside burger stand known for ShackBurgers and crinkle-cut fries.",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    source: "yelp",
    phone: "+1 212-889-6600",
    hours: "Daily 10:30am–11pm",
    tags: ["Burgers", "American", "Casual", "Fast Casual"],
  },
  {
    id: "p4",
    name: "The Metropolitan Museum of Art",
    category: "museum",
    address: "1000 5th Ave",
    city: "New York",
    lat: 40.7794,
    lng: -73.9632,
    rating: 4.8,
    reviewCount: 54321,
    priceLevel: 2,
    description: "One of the world's largest art museums spanning 5,000 years of culture.",
    imageUrl: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?w=600&q=80",
    source: "tripadvisor",
    hours: "Sun–Thu 10am–5pm, Fri–Sat 10am–9pm",
    tags: ["Museum", "Art", "Culture", "History"],
  },
  {
    id: "p5",
    name: "Café Mogador",
    category: "cafe",
    address: "101 St. Marks Pl",
    city: "New York",
    lat: 40.7264,
    lng: -73.9862,
    rating: 4.5,
    reviewCount: 3214,
    priceLevel: 2,
    description: "East Village institution serving Moroccan-inspired brunch since 1983.",
    imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80",
    source: "yelp",
    phone: "+1 212-677-2226",
    hours: "Daily 9am–12am",
    tags: ["Moroccan", "Brunch", "Coffee", "East Village"],
  },
  {
    id: "p6",
    name: "DUMBO",
    category: "attraction",
    address: "DUMBO, Brooklyn",
    city: "New York",
    lat: 40.7033,
    lng: -73.9891,
    rating: 4.7,
    reviewCount: 12987,
    priceLevel: 1,
    description: "Iconic cobblestoned neighborhood with the famous Manhattan Bridge arch view.",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    source: "tripadvisor",
    tags: ["Neighborhood", "Photography", "Bridge View", "Brooklyn"],
  },
  // Tokyo
  {
    id: "p7",
    name: "Sukiyabashi Jiro",
    category: "restaurant",
    address: "Tsukamoto Sogyo Bldg, Chuo City",
    city: "Tokyo",
    lat: 35.6722,
    lng: 139.7635,
    rating: 4.9,
    reviewCount: 1834,
    priceLevel: 4,
    description: "World-famous sushi restaurant from Jiro Ono, subject of the documentary Jiro Dreams of Sushi.",
    imageUrl: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80",
    source: "tripadvisor",
    tags: ["Sushi", "Japanese", "Fine Dining", "Michelin Star"],
  },
  {
    id: "p8",
    name: "Senso-ji Temple",
    category: "attraction",
    address: "2-3-1 Asakusa, Taito City",
    city: "Tokyo",
    lat: 35.7148,
    lng: 139.7967,
    rating: 4.8,
    reviewCount: 76543,
    priceLevel: 1,
    description: "Tokyo's oldest and most significant Buddhist temple, founded in 628 AD.",
    imageUrl: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=600&q=80",
    source: "tripadvisor",
    hours: "Grounds: 24 hours. Main hall: 6am–5pm",
    tags: ["Temple", "Buddhist", "Historic", "Asakusa"],
  },
  // Paris
  {
    id: "p9",
    name: "Café de Flore",
    category: "cafe",
    address: "172 Bd Saint-Germain, 75006",
    city: "Paris",
    lat: 48.8541,
    lng: 2.3322,
    rating: 4.3,
    reviewCount: 9876,
    priceLevel: 3,
    description: "Historic Left Bank café frequented by Sartre, Simone de Beauvoir, and countless artists.",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&q=80",
    source: "tripadvisor",
    phone: "+33 1 45 48 55 26",
    hours: "Daily 7am–1:30am",
    tags: ["Café", "Historic", "French", "Saint-Germain"],
  },
  {
    id: "p10",
    name: "Musée du Louvre",
    category: "museum",
    address: "Rue de Rivoli, 75001",
    city: "Paris",
    lat: 48.8606,
    lng: 2.3376,
    rating: 4.7,
    reviewCount: 102456,
    priceLevel: 2,
    description: "The world's largest art museum and a historic monument housing the Mona Lisa.",
    imageUrl: "https://images.unsplash.com/photo-1565072952791-49f72f6b6765?w=600&q=80",
    source: "tripadvisor",
    hours: "Mon, Thu, Sat–Sun: 9am–6pm. Wed, Fri: 9am–9:45pm. Closed Tue.",
    tags: ["Museum", "Art", "History", "Iconic"],
  },
];

export const MOCK_EXPERIENCES: Experience[] = [
  {
    id: "e1",
    title: "Skip-the-Line Eiffel Tower Summit Tour",
    category: "tour",
    city: "Paris",
    country: "France",
    durationHours: 2.5,
    price: 89,
    currency: "USD",
    rating: 4.7,
    reviewCount: 12876,
    imageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600&q=80",
    description: "Skip the long queues and ascend to the top of the Eiffel Tower with a small group. Includes a knowledgeable guide and champagne at the summit.",
    highlights: ["Skip-the-line access", "Summit level included", "Champagne toast", "Small group (max 12)"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Skip+the+Line+Eiffel+Tower+Summit+Tour",
    groupSize: "Max 12",
    languages: ["English", "French", "Spanish"],
    included: ["Guide", "Skip-the-line ticket", "Champagne"],
  },
  {
    id: "e2",
    title: "Tokyo Street Food Night Tour in Shinjuku",
    category: "food",
    city: "Tokyo",
    country: "Japan",
    durationHours: 3,
    price: 62,
    currency: "USD",
    rating: 4.9,
    reviewCount: 4532,
    imageUrl: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&q=80",
    description: "Explore the neon-lit streets of Shinjuku tasting yakitori, ramen, takoyaki, and more at local izakayas with a local foodie guide.",
    highlights: ["8+ tastings included", "Local izakaya access", "Night market visit", "Sake pairing"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Tokyo+Street+Food+Night+Tour+Shinjuku",
    groupSize: "Max 8",
    languages: ["English", "Japanese"],
    included: ["All food tastings", "Non-alcoholic drinks", "Guide"],
  },
  {
    id: "e3",
    title: "New York City Helicopter Tour",
    category: "adventure",
    city: "New York",
    country: "USA",
    durationHours: 0.5,
    price: 219,
    currency: "USD",
    rating: 4.8,
    reviewCount: 7841,
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&q=80",
    description: "Soar over Manhattan's iconic skyline including Central Park, the Brooklyn Bridge, and the Statue of Liberty in a thrilling 15-minute helicopter ride.",
    highlights: ["Flight over Manhattan", "Statue of Liberty view", "Brooklyn Bridge aerial", "Photo opportunities"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=New+York+City+Helicopter+Tour",
    groupSize: "Max 6",
    languages: ["English"],
    included: ["Pilot narration", "Headsets", "Hotel pickup available"],
  },
  {
    id: "e4",
    title: "Colosseum Underground & Arena Floor Tour",
    category: "culture",
    city: "Rome",
    country: "Italy",
    durationHours: 2,
    price: 75,
    currency: "USD",
    rating: 4.9,
    reviewCount: 9102,
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80",
    description: "Access restricted underground chambers and stand on the arena floor where gladiators once fought. Skip-the-line entry included.",
    highlights: ["Underground level access", "Arena floor access", "Skip-the-line", "Expert historian guide"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Colosseum+Underground+Arena+Floor+Tour",
    groupSize: "Max 15",
    languages: ["English", "Italian", "Spanish", "French"],
    included: ["Entrance tickets", "Guide", "Underground access"],
  },
  {
    id: "e5",
    title: "Barcelona Tapas & Wine Evening Walk",
    category: "food",
    city: "Barcelona",
    country: "Spain",
    durationHours: 3.5,
    price: 79,
    currency: "USD",
    rating: 4.8,
    reviewCount: 5234,
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80",
    description: "Wander through El Born and Gothic Quarter stopping at four local tapas bars for traditional pintxos, croquetas, and Spanish wines.",
    highlights: ["4 tapas bars", "Wine & cava pairings", "Gothic Quarter stroll", "Local guide"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Barcelona+Tapas+Wine+Evening+Walk",
    groupSize: "Max 10",
    languages: ["English", "Spanish"],
    included: ["All tastings", "Wines & drinks", "Guide"],
  },
  {
    id: "e6",
    title: "Kyoto Geisha District Walking Tour",
    category: "culture",
    city: "Kyoto",
    country: "Japan",
    durationHours: 2,
    price: 45,
    currency: "USD",
    rating: 4.7,
    reviewCount: 3120,
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    description: "Stroll through the preserved wooden machiya townhouses of Gion and learn about geisha culture with a local historian.",
    highlights: ["Gion district", "Traditional machiya", "Geisha culture history", "Photo spots"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Kyoto+Geisha+District+Walking+Tour",
    groupSize: "Max 12",
    languages: ["English", "Japanese"],
    included: ["Guide", "Entrance fees"],
  },
  {
    id: "e7",
    title: "Thai Cooking Class with Market Visit",
    category: "food",
    city: "Bangkok",
    country: "Thailand",
    durationHours: 4,
    price: 55,
    currency: "USD",
    rating: 4.9,
    reviewCount: 8765,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    description: "Shop for fresh ingredients at a local market then cook 4 Thai dishes from scratch in a traditional home kitchen setting.",
    highlights: ["Market tour", "Cook 4 dishes", "Recipe booklet to keep", "Vegetarian options"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Thai+Cooking+Class+Market+Visit+Bangkok",
    groupSize: "Max 8",
    languages: ["English", "Thai"],
    included: ["Market visit", "All ingredients", "Lunch", "Recipe booklet"],
  },
  {
    id: "e8",
    title: "Machu Picchu Guided Sunrise Tour",
    category: "adventure",
    city: "Cusco",
    country: "Peru",
    durationHours: 6,
    price: 98,
    currency: "USD",
    rating: 4.9,
    reviewCount: 6432,
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&q=80",
    description: "Beat the crowds and witness the sunrise over Machu Picchu with a certified archaeologist guide. Early bus entry included.",
    highlights: ["Sunrise entry", "Archaeologist guide", "Intihuatana stone", "Sun Gate hike option"],
    provider: "Viator",
    source: "viator",
    bookingUrl: "https://www.viator.com/search?text=Machu+Picchu+Guided+Sunrise+Tour",
    groupSize: "Max 16",
    languages: ["English", "Spanish"],
    included: ["Entry tickets", "Guide", "Bus transfer"],
  },
];

export const MOCK_ESIM_PLANS: EsimPlan[] = [
  // USA
  {
    id: "esim-us-1",
    carrier: "AT&T",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    dataGb: 1,
    durationDays: 7,
    priceUsd: 4.50,
    coverage: "local",
    network: "4G/LTE",
    topUpAvailable: true,
    hotspotAllowed: false,
    source: "airalo",
    popular: false,
  },
  {
    id: "esim-us-2",
    carrier: "T-Mobile",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    dataGb: 5,
    durationDays: 15,
    priceUsd: 13.00,
    coverage: "local",
    network: "5G",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: true,
  },
  {
    id: "esim-us-3",
    carrier: "Verizon",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    dataGb: 10,
    durationDays: 30,
    priceUsd: 23.00,
    coverage: "local",
    network: "5G",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: false,
  },
  // Japan
  {
    id: "esim-jp-1",
    carrier: "IIJmio",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    dataGb: 3,
    durationDays: 15,
    priceUsd: 9.00,
    coverage: "local",
    network: "4G/LTE",
    topUpAvailable: false,
    hotspotAllowed: true,
    source: "airalo",
    popular: true,
  },
  {
    id: "esim-jp-2",
    carrier: "Softbank",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    dataGb: 10,
    durationDays: 30,
    priceUsd: 21.00,
    coverage: "local",
    network: "5G",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: false,
  },
  // France / Europe
  {
    id: "esim-eu-1",
    carrier: "Orange",
    country: "France",
    countryCode: "FR",
    flag: "🇫🇷",
    dataGb: 5,
    durationDays: 30,
    priceUsd: 11.00,
    coverage: "local",
    network: "4G/LTE",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: false,
  },
  {
    id: "esim-eu-2",
    carrier: "Ubigi",
    country: "Europe (39 countries)",
    countryCode: "EU",
    flag: "🇪🇺",
    dataGb: 10,
    durationDays: 30,
    priceUsd: 19.00,
    coverage: "regional",
    network: "4G/LTE",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: true,
  },
  {
    id: "esim-eu-3",
    carrier: "Airalo Global",
    country: "Europe (39 countries)",
    countryCode: "EU",
    flag: "🇪🇺",
    dataGb: 20,
    durationDays: 30,
    priceUsd: 33.00,
    coverage: "regional",
    network: "5G",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: false,
  },
  // Thailand
  {
    id: "esim-th-1",
    carrier: "AIS",
    country: "Thailand",
    countryCode: "TH",
    flag: "🇹🇭",
    dataGb: 15,
    durationDays: 30,
    priceUsd: 12.00,
    coverage: "local",
    network: "4G/LTE",
    topUpAvailable: false,
    hotspotAllowed: true,
    source: "airalo",
    popular: true,
  },
  // Global
  {
    id: "esim-global-1",
    carrier: "Airalo Global",
    country: "Global (190+ countries)",
    countryCode: "WW",
    flag: "🌍",
    dataGb: 5,
    durationDays: 30,
    priceUsd: 29.00,
    coverage: "global",
    network: "4G/LTE",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: true,
  },
  {
    id: "esim-global-2",
    carrier: "GigSky",
    country: "Global (190+ countries)",
    countryCode: "WW",
    flag: "🌍",
    dataGb: 10,
    durationDays: 30,
    priceUsd: 49.00,
    coverage: "global",
    network: "4G/LTE",
    topUpAvailable: true,
    hotspotAllowed: true,
    source: "airalo",
    popular: false,
  },
];

export const DEEPL_LANGUAGES = [
  { code: "auto", name: "Auto-detect" },
  { code: "BG", name: "Bulgarian" },
  { code: "CS", name: "Czech" },
  { code: "DA", name: "Danish" },
  { code: "DE", name: "German" },
  { code: "EL", name: "Greek" },
  { code: "EN", name: "English" },
  { code: "ES", name: "Spanish" },
  { code: "ET", name: "Estonian" },
  { code: "FI", name: "Finnish" },
  { code: "FR", name: "French" },
  { code: "HU", name: "Hungarian" },
  { code: "ID", name: "Indonesian" },
  { code: "IT", name: "Italian" },
  { code: "JA", name: "Japanese" },
  { code: "KO", name: "Korean" },
  { code: "LT", name: "Lithuanian" },
  { code: "LV", name: "Latvian" },
  { code: "NB", name: "Norwegian" },
  { code: "NL", name: "Dutch" },
  { code: "PL", name: "Polish" },
  { code: "PT", name: "Portuguese" },
  { code: "RO", name: "Romanian" },
  { code: "RU", name: "Russian" },
  { code: "SK", name: "Slovak" },
  { code: "SL", name: "Slovenian" },
  { code: "SV", name: "Swedish" },
  { code: "TR", name: "Turkish" },
  { code: "UK", name: "Ukrainian" },
  { code: "ZH", name: "Chinese" },
];

export const POPULAR_CITIES = [
  { name: "New York", country: "USA", lat: 40.7128, lng: -74.006, emoji: "🗽" },
  { name: "Tokyo", country: "Japan", lat: 35.6762, lng: 139.6503, emoji: "🗼" },
  { name: "Paris", country: "France", lat: 48.8566, lng: 2.3522, emoji: "🥐" },
  { name: "London", country: "UK", lat: 51.5074, lng: -0.1278, emoji: "🎡" },
  { name: "Rome", country: "Italy", lat: 41.9028, lng: 12.4964, emoji: "🏛️" },
  { name: "Barcelona", country: "Spain", lat: 41.3851, lng: 2.1734, emoji: "🎨" },
  { name: "Bangkok", country: "Thailand", lat: 13.7563, lng: 100.5018, emoji: "🛺" },
  { name: "Kyoto", country: "Japan", lat: 35.0116, lng: 135.7681, emoji: "⛩️" },
];

export const COMMON_PHRASES = [
  { en: "Where is the bathroom?", category: "Essentials" },
  { en: "How much does this cost?", category: "Shopping" },
  { en: "I would like to order this.", category: "Dining" },
  { en: "Do you speak English?", category: "Essentials" },
  { en: "Can you help me?", category: "Essentials" },
  { en: "I have a reservation.", category: "Accommodation" },
  { en: "What time does it close?", category: "Sightseeing" },
  { en: "Is there WiFi here?", category: "Essentials" },
  { en: "Can I have the check please?", category: "Dining" },
  { en: "How do I get to the airport?", category: "Transport" },
  { en: "I am allergic to nuts.", category: "Dining" },
  { en: "Please call a taxi.", category: "Transport" },
];
